# Generated by Django 2.2.4 on 2019-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20191019_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='saldo',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
