# Generated by Django 2.2.4 on 2019-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20190915_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
