# Generated by Django 2.2.4 on 2019-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_auto_20191020_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
