# Generated by Django 2.2.4 on 2019-11-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default='Titans de Ouro', help_text='nome da empresa', max_length=100),
        ),
    ]
