# Generated by Django 2.2.4 on 2019-10-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_auto_20191006_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(help_text='nome do departamento', max_length=70),
        ),
    ]
