# Generated by Django 2.2.4 on 2019-10-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
    ]
