# Generated by Django 2.2.4 on 2019-10-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_auto_20191021_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
